
name: BUILD v8

on:
  push:
    branches: [ master ]
    
jobs:
  Compile:
    name:Compile Android
    runs-on:ubuntu-latest
    steps:
    - name: Ready For Project
      run: |
        sudo apt update
        sudo apt upgrade
        sudo apt install python
        sudo apt install python3
        sudo apt install python-pip
        sudo apt install python3-pip
        sudo apt install git
        sudo apt install repo
    - name: Repo Code
      run: |
        mkdir Android_code
        cd Android_code
        repo init -u https://github.com/exthmui/android.git -b exthm-11
        repo sync
    - name: test
      run: |
        ls
