name: "Use action to compile android kernel"

on: push

jobs:
  ready_compile_env:
    name: Compile kernel
    runs-on: ubuntu-latest
    steps:
    - name: Ready Compile
      run: |
        sudo apt update
        sudo apt upgrade
        sudo apt install -y openssl make python libssh-dev unzip git wget build-essential zip bc wget unzip p7zip-full git
        wget https://github.com/kdrag0n/proton-clang/archive/refs/tags/20210522.zip
        unzip ./20210522.zip
    - name: find_location_file
      run: |
        pwd
        ls
    
