name: "安装环境"

on:
  workflow_dispatch:
    inputs:

env:
  ARCHOSUB: 'arm64'
  KERNEL_DIR: 'kernel_source'
  COMPILE_THREAD: '$(nproc --all)' # $(nproc --all) cpu核心数

jobs:
  proton:
    name: 安装环境
    runs-on: ubuntu-latest
    steps:
    - name: Set up Clang
      uses: egor-tensin/setup-clang@v1
      with:
        version: latest
        platform: x64
    - name: Set up crossc
      runs: |
        sudo bash setup_enviroment.sh